const foodData: Food[] = [
  {
    name: "불고기",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "떡볶이",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스시",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "카레라이스",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "햄버거",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "짜장면",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "짬뽕",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "김치찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "비빔밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "라면",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "돈가스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "회덮밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "피자",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "탕수육",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "마파두부",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오므라이스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "김밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "케밥",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "달걀볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "돼지고기 김치찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "해물파전",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우 볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "크림 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "순두부찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "돈코츠 라멘",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "제육볶음",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "우동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: true,
  },
  {
    name: "토마토 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "달걀 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "양송이 수프",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "해물 칼국수",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "크로와상 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "야채비빔밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "중국식 볶음면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "야키소바",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "리소토",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "라조기",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "카레우동",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "나시고렝",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "미소라멘",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "두부조림",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "가지볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "고등어구이",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "참치마요 덮밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우튀김",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칼국수",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "팟타이",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "잡채밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "새우볶음면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "비빔국수",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈 라면",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "함박 스테이크",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "수제비",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "오코노미야끼",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "김치볶음밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "게살죽",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "돈까스 덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "단팥빵",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "치킨 커리",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "치즈 돈까스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "연어 스테이크",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "비프 스테이크",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "연어 덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "야채 튀김",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "육개장",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "닭가슴살 샐러드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "참치 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "라조면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "해물 짬뽕밥",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "크림 스프",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "바게트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오징어 볶음밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "갈비탕",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "생선구이",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오리 주물럭",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "양념 치킨 샌드위치",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "메밀국수",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "스파게티",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "매운탕",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: false,
  },
  {
    name: "카레밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "계란국",
    spicy: false,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "치킨 샐러드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "두부 샐러드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "어묵국",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: true,
  },
  {
    name: "참치김밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "잡채",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "쌀국수",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "계란밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "돼지고기 덮밥",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우 스파게티",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "가지 덮밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "비빔냉면",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "명란 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "우렁된장찌개",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "고구마 빵",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오징어 덮밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: false,
  },
  {
    name: "오리불고기",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "돈부리",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "고등어 조림",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: false,
  },
  {
    name: "해물파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "미트볼 스파게티",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "유부초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "생선초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "단팥죽",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "순대국밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "김치전",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "해물순두부찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "야채죽",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "베이컨 에그 베이글",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우 카레",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "바질 페스토 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "간장 게장",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스테이크",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "닭죽",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "크림 리조또",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "토마토 라면",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "낙지 볶음밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "크루아상",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "감자 수프",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "돼지국밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "삼겹살 덮밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "고등어 초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "육회 비빔밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "매운갈비찜",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "돼지고기 김밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "닭갈비 덮밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "불고기버거",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "연어 아보카도 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치킨 시저 샐러드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "떡국",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "두부 덮밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "미소된장국",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "크림 치즈 베이글",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "오징어볶음 덮밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "채소볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치킨 카레",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "쇠고기 볶음밥",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "크림스프 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: true,
  },
  {
    name: "달걀라면",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "연어 베이글",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "비프 타코",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "새우 리조또",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "참치 크로와상",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "양송이 리조또",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "명란 파스타",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "카츠산도",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 새우 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "탄탄멘",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "게살 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "텐동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "후토마키",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "스키야키",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "소고기 라멘",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "해물 야키소바",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "에비카츠 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "우나기동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오코노미야끼",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "소바",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "가츠동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "마파두부면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "짜장밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "깐풍기",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "고추잡채",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "해파리냉채",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "유린기",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "단팥빵",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "굴짬뽕",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "소고기 탕수육",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "비프롤 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "춘권",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "라이스페이퍼 롤",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈불닭 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "해물 떡볶이",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "불고기 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "바질 토마토 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "사천식 볶음면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우 완탕면",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "딤섬",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "깐쇼새우",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "사케동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "포크 커틀릿",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "연어 아보카도 덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "대게 스프",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "연어 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "완탕",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "야끼니꾸 덮밥",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "매운 해물 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "사천식 마파두부",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "고등어회 덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "야키소바 파스타",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "게살 크로와상",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "간장치킨 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "차슈 라멘",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "새우 타코야키",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "매운 새우덮밥",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "야끼우동",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "매운 어묵우동",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "카이센동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "포크 버거",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "에그타르트",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "바비큐 치킨 빵",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "갈릭 쉬림프 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "연어 아보카도 베이글",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "텐동 텐야",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "야채 카레",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오징어 먹물 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "해물 야끼소바",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "타마고 산도",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈 토스트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "미트볼 라자냐",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "불닭 샌드위치",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "가라아게 덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "연어 스시 롤",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "새우 완탕",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "닭가슴살 파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "간장 새우 덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "미트볼 스파게티",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "양념 치킨 버거",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "우삼겹 덮밥",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 치즈 프라이즈",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "중국식 볶음 우동",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "게살 볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "돼지고기 양배추 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "매운 해물 볶음면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "양념 소시지 샌드위치",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "치즈 돈까스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "연어 스테이크 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "매운 돼지고기 볶음밥",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "두부 라면",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: true,
  },
  {
    name: "단팥죽",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "크림 치즈 베이글 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "갈릭 치킨 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "해물 해장국",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "마파두부 덮밥",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "가지 덮밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "연어 카레 덮밥",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "새우 볶음 우동",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "카레 파스타",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "아보카도 토스트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "호두파이",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "딸기 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "초콜릿 크로와상",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈 크래커",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "블루베리 머핀",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "바나나 브레드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "시나몬 롤",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "초코칩 쿠키",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "마카롱",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "허니 브레드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "베리 요거트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈 케이크",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "베이컨 에그 머핀",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "크랩 랑군",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "슈크림 빵",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "생크림 케이크",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "딸기 타르트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "코코넛 마카롱",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "망고 푸딩",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "피넛버터 토스트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "연유 토스트",
    spicy: false,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "오트밀 쿠키",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "초코 브라우니",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "크림 치즈 페이스트리",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "사과 타르트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "녹차 마카롱",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "프렌치 바게트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "딸기 생크림 샌드위치",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "오징어 먹물빵",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "매콤한 새우칩",
    spicy: true,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "매운맛 감자칩",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "크래커와 치즈",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈 스틱",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "에그 스크램블",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "갈릭 브레드",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "연어 크로스티니",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "아보카도 딥과 칩",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "토마토 브루스케타",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치킨 너겟",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "미니 피자",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "연어 롤",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "감자 고로케",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "감자 치즈볼",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "피칸 타르트",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 칩스",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "핫 소세지",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 팝콘",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 피넛",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "고추 과자",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 너겟",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 킹크랩",
    spicy: true,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 베이컨",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 치즈볼",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "핫 치킨 윙",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫도그",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫 치킨 너겟",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 새우볼",
    spicy: true,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 치킨바",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫소스 너겟",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "고추장 크래커",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 어묵바",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 페이스트리",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스파이시 브레드스틱",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "고추 치즈볼",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 크래커",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 치킨 바",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫 크랩 케이크",
    spicy: true,
    meal: false,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 소시지",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 치킨 스트립",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫 소시지 롤",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리치즈 크래커",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 새우 크래커",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 치킨 볼",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "핫치킨 샌드위치",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스파이시 비프 저키",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 치킨 바이트",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스파이시 어묵볼",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "핫 소시지 바",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 치즈 토스트",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "핫치킨 페이스트리",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스파이시 핫도그",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칠리 치즈 프라이즈",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 스낵 믹스",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "고추 치킨 크로켓",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 소시지",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫치킨 프레첼",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 칠리 크래커",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "고추 치즈 토스트",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 치킨바",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스파이시 치킨 스트립",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "핫 크래커",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "칠리 감자 프라이",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "스파이시 닭봉",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
];

export default foodData;
