type Food = {
  name: string;
  spicy: boolean;
  meal: boolean;
  cuisine: "한식" | "중식" | "양식" | "일식";
  containsMeat: boolean;
  containsSeafood: boolean;
  base: "밥" | "빵" | "면";
  expensive: boolean;
  lowCalorie: boolean;
  withSoup: boolean;
  light: boolean;
};

const foodData: Food[] = [
  {
    name: "김치찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "비빔밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "짬뽕",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "스시",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "제육볶음",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "된장찌개",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "탕수육",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "피자",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "돈까스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "칼국수",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "치킨",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "라면",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "낙지볶음",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "미역국",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "파스타",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "스테이크",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "쌀국수",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "깐풍기",
    spicy: true,
    meal: false,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "부대찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "연어샐러드",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오꼬노미야끼",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "잡채",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: true,
  },
  {
    name: "삼겹살",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "아구찜",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "문어초회",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "닭갈비",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "떡볶이",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "전",
    spicy: false,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우볶음밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "양념치킨",
    spicy: true,
    meal: false,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "부타동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "피쉬앤칩스",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "굴국밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "양꼬치",
    spicy: true,
    meal: false,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "치즈돈까스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "치킨버거",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "카레라이스",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "우동",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "해물찜",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "훈제연어",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "삼계탕",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "크림파스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "홍합탕",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "양지국밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "비빔국수",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "차슈덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "해물파전",
    spicy: false,
    meal: false,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "양장피",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: true,
    containsSeafood: true,
    base: "면",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "후라이드치킨",
    spicy: false,
    meal: false,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "물냉면",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "비빔냉면",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "연어초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "피쉬타코",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "갈비탕",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "순두부찌개",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "크로와상",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "고로케",
    spicy: false,
    meal: false,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "햄버거",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "낙지볶음밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치킨윙",
    spicy: true,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "굴비구이",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "쭈꾸미볶음",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "샐러드",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: false,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "갈비찜",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "참치김밥",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오므라이스",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "카레",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우튀김",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "소세지볶음",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "가지덮밥",
    spicy: false,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "카레돈까스",
    spicy: true,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "멸치볶음",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치즈라면",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: false,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "해물짬뽕",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: true,
    light: false,
  },
  {
    name: "양념게장",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "불고기",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "깐쇼새우",
    spicy: true,
    meal: true,
    cuisine: "중식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "치킨마요덮밥",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "연어롤",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "오징어덮밥",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "유부초밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "감바스",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "빵",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "햄치즈샌드위치",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "새우튀김덮밥",
    spicy: false,
    meal: true,
    cuisine: "일식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "랍스타",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "치킨카레",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "샌드위치",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "훈제오리",
    spicy: false,
    meal: true,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "야끼소바",
    spicy: true,
    meal: true,
    cuisine: "일식",
    containsMeat: true,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "소고기죽",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: true,
    containsSeafood: false,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "한치볶음",
    spicy: true,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: false,
    lowCalorie: true,
    withSoup: false,
    light: true,
  },
  {
    name: "전복죽",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "밥",
    expensive: true,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
  {
    name: "소세지빵",
    spicy: false,
    meal: false,
    cuisine: "양식",
    containsMeat: true,
    containsSeafood: false,
    base: "빵",
    expensive: false,
    lowCalorie: false,
    withSoup: false,
    light: false,
  },
  {
    name: "멸치국수",
    spicy: false,
    meal: true,
    cuisine: "한식",
    containsMeat: false,
    containsSeafood: true,
    base: "면",
    expensive: false,
    lowCalorie: true,
    withSoup: true,
    light: true,
  },
];

export default foodData;
